// Code generated by "stringer -type Direction -trimprefix Direction"; DO NOT EDIT.

package geo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DirectionUndefined-0]
	_ = x[DirectionNorth-1]
	_ = x[DirectionSouth-2]
	_ = x[DirectionWest-3]
	_ = x[DirectionEast-4]
}

const _Direction_name = "UndefinedNorthSouthWestEast"

var _Direction_index = [...]uint8{0, 9, 14, 19, 23, 27}

func (i Direction) String() string {
	if i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
