name: BenchDiff
on: [push, pull_request]
jobs:
  test:
    name: BenchDiff
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: 1.23.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install cob
        run: curl -sfL https://raw.githubusercontent.com/knqyf263/cob/master/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Run Benchmark
        run: cob
