name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: 1.23.1
        id: go

      - name: Install gomobile
        run: go install golang.org/x/mobile/cmd/gomobile@latest

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run Test
        run: make test
